[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "process-waste"
version = "0.2.0"
description = "Business process waste identification"
authors = ["Ihar Suvorau <ihar.suvorau@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.scripts]
process-waste = "waste.cli:main"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.0.4"
pandas = "^1.4.1"
pytest = "^7.0.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.17.0"

[virtualenvs]
in-project = true
