name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9' ]
        r-version: [ '4.1' ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: Setting Rscript bin path
        shell: bash
        run: |
          export RSCRIPT_BIN_PATH=`which Rscript`
      - name: Install dependencies
        shell: bash
        run: |
          ./install.sh
      - name: Upload the build
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.python-version }}
          path: dist
      - name: Smoke Test
        shell: bash
        run: |
          source venv/bin/activate
          process-waste --help
      - name: Test the build
        shell: bash
        run: |
          source venv/bin/activate
          pytest -v --cov=. --junitxml=pytest_coverage.xml --cov-report=term tests | tee pytest-coverage.log
      - name: Upload the coverage report
        uses: actions/upload-artifact@v3
        with:
          name: pytest_coverage.xml
          path: pytest_coverage.xml
      - name: Test Coverage
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: pytest-coverage.log
          junitxml-path: pytest_coverage.xml
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          flag-name: All Tests