name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9' ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash
        run: |
          ./install.sh
      - name: Upload the build
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.python-version }}
          path: dist
      - name: Upload the environment
        uses: actions/upload-artifact@v3
        with:
          name: venv
          path: venv
  test:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      matrix:
        python-version: [ '3.9' ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download the build
        uses: actions/download-artifact@v3
        with:
          name: build-${{ matrix.python-version }}
          path: dist
      - name: Download the environment
        uses: actions/download-artifact@v3
        with:
          name: venv
          path: venv
      - name: Test the build
        run: |
          source venv/bin/activate
          pytest -v